baseURL = 'https://soucoup.com/'
languageCode = 'en-us'
title = 'soucoup'
theme = 'terminal'

[pagination]
  pagerSize = 5

[params]
  # Terminal theme settings
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false

  # Code highlighting
  [params.highlight]
    enabled = true
    style = "monokai"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "soucoup"
    subtitle = "Developer thoughts on AI, code & the tech world"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "subscribe"
        name = "Subscribe"
        url = "/subscribe"
        weight = 3
